name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.43.0-alpine
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/check/check.sh

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-beta2
          stable: false
      - run: make unit-test